# Generated by Django 4.1 on 2022-10-05 18:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_rename_article_tsk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tsk',
            new_name='Task',
        ),
    ]
